# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../stopsignaltask_QtProject/mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.label_2 = QtWidgets.QLabel(self.centralWidget)
        self.label_2.setGeometry(QtCore.QRect(280, 10, 301, 61))
        font = QtGui.QFont()
        font.setFamily("Baskerville")
        self.label_2.setFont(font)
        self.label_2.setLineWidth(1)
        self.label_2.setObjectName("label_2")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralWidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(420, 140, 351, 261))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.rtDisplay = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.rtDisplay.setContentsMargins(11, 11, 11, 11)
        self.rtDisplay.setSpacing(6)
        self.rtDisplay.setObjectName("rtDisplay")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.centralWidget)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(620, 430, 152, 100))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.testLaser_button = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.testLaser_button.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.testLaser_button.setFont(font)
        self.testLaser_button.setObjectName("testLaser_button")
        self.verticalLayout_2.addWidget(self.testLaser_button)
        self.testReward_button = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.testReward_button.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.testReward_button.setFont(font)
        self.testReward_button.setObjectName("testReward_button")
        self.verticalLayout_2.addWidget(self.testReward_button)
        self.testStopSignal_button = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.testStopSignal_button.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.testStopSignal_button.setFont(font)
        self.testStopSignal_button.setObjectName("testStopSignal_button")
        self.verticalLayout_2.addWidget(self.testStopSignal_button)
        self.descriptionalLabel = QtWidgets.QLabel(self.centralWidget)
        self.descriptionalLabel.setGeometry(QtCore.QRect(50, 210, 71, 141))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.descriptionalLabel.setFont(font)
        self.descriptionalLabel.setText("")
        self.descriptionalLabel.setObjectName("descriptionalLabel")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralWidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(150, 140, 231, 261))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.stopPerfLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.stopPerfLabel.setFont(font)
        self.stopPerfLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.stopPerfLabel.setObjectName("stopPerfLabel")
        self.gridLayout.addWidget(self.stopPerfLabel, 3, 1, 1, 1)
        self.goPerfLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.goPerfLabel.setFont(font)
        self.goPerfLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.goPerfLabel.setObjectName("goPerfLabel")
        self.gridLayout.addWidget(self.goPerfLabel, 2, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.label_5.setFont(font)
        self.label_5.setTextFormat(QtCore.Qt.AutoText)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 0, 1, 1)
        self.timeElapsedLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.timeElapsedLabel.setFont(font)
        self.timeElapsedLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.timeElapsedLabel.setObjectName("timeElapsedLabel")
        self.gridLayout.addWidget(self.timeElapsedLabel, 1, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 2, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 3, 0, 1, 1)
        self.trialNumLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.trialNumLabel.setFont(font)
        self.trialNumLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.trialNumLabel.setObjectName("trialNumLabel")
        self.gridLayout.addWidget(self.trialNumLabel, 0, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 1, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 4, 0, 1, 1)
        self.ssrtLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.ssrtLabel.setFont(font)
        self.ssrtLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.ssrtLabel.setObjectName("ssrtLabel")
        self.gridLayout.addWidget(self.ssrtLabel, 4, 1, 1, 1)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.centralWidget)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(90, 450, 381, 71))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.start_button = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.start_button.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.start_button.setFont(font)
        self.start_button.setAutoDefault(False)
        self.start_button.setDefault(False)
        self.start_button.setFlat(False)
        self.start_button.setObjectName("start_button")
        self.horizontalLayout_3.addWidget(self.start_button)
        self.end_button = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.end_button.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.end_button.sizePolicy().hasHeightForWidth())
        self.end_button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.end_button.setFont(font)
        self.end_button.setObjectName("end_button")
        self.horizontalLayout_3.addWidget(self.end_button)
        self.label_4 = QtWidgets.QLabel(self.centralWidget)
        self.label_4.setGeometry(QtCore.QRect(160, 80, 221, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.label = QtWidgets.QLabel(self.centralWidget)
        self.label.setGeometry(QtCore.QRect(40, 80, 81, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_10 = QtWidgets.QLabel(self.centralWidget)
        self.label_10.setGeometry(QtCore.QRect(480, 80, 271, 61))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.runingLabel = QtWidgets.QLabel(self.centralWidget)
        self.runingLabel.setEnabled(True)
        self.runingLabel.setGeometry(QtCore.QRect(70, 160, 21, 21))
        self.runingLabel.setText("")
        self.runingLabel.setPixmap(QtGui.QPixmap(":/off.png"))
        self.runingLabel.setScaledContents(False)
        self.runingLabel.setObjectName("runingLabel")
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menuBar.setObjectName("menuBar")
        self.menuStop_Signal_Task = QtWidgets.QMenu(self.menuBar)
        self.menuStop_Signal_Task.setObjectName("menuStop_Signal_Task")
        self.menuSettings = QtWidgets.QMenu(self.menuBar)
        self.menuSettings.setObjectName("menuSettings")
        self.menuHelp = QtWidgets.QMenu(self.menuBar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mainToolBar.sizePolicy().hasHeightForWidth())
        self.mainToolBar.setSizePolicy(sizePolicy)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.actionNew_Training = QtWidgets.QAction(MainWindow)
        self.actionNew_Training.setObjectName("actionNew_Training")
        self.actionSerial_Port = QtWidgets.QAction(MainWindow)
        self.actionSerial_Port.setObjectName("actionSerial_Port")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.menuStop_Signal_Task.addAction(self.actionNew_Training)
        self.menuSettings.addAction(self.actionSerial_Port)
        self.menuHelp.addAction(self.actionAbout)
        self.menuBar.addAction(self.menuStop_Signal_Task.menuAction())
        self.menuBar.addAction(self.menuSettings.menuAction())
        self.menuBar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "SST"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:24pt; font-weight:600;\">Stop Signal Task</span></p></body></html>"))
        self.testLaser_button.setText(_translate("MainWindow", "TestLaser"))
        self.testReward_button.setText(_translate("MainWindow", "TestReward"))
        self.testStopSignal_button.setText(_translate("MainWindow", "TestStopSignal"))
        self.stopPerfLabel.setText(_translate("MainWindow", "0"))
        self.goPerfLabel.setText(_translate("MainWindow", "0"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Trials Finished:</span></p></body></html>"))
        self.timeElapsedLabel.setText(_translate("MainWindow", "0"))
        self.label_7.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Go Performance:</span></p></body></html>"))
        self.label_8.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Stop Performance:</span></p></body></html>"))
        self.trialNumLabel.setText(_translate("MainWindow", "0"))
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Time Elapsed:</span></p></body></html>"))
        self.label_9.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">SSRT:</span></p></body></html>"))
        self.ssrtLabel.setText(_translate("MainWindow", "0ms"))
        self.start_button.setText(_translate("MainWindow", "Start"))
        self.end_button.setText(_translate("MainWindow", "End"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Statistics</span></p></body></html>"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Status</span></p></body></html>"))
        self.label_10.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Online RT Distribution</span></p></body></html>"))
        self.menuStop_Signal_Task.setTitle(_translate("MainWindow", "New"))
        self.menuSettings.setTitle(_translate("MainWindow", "Settings"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionNew_Training.setText(_translate("MainWindow", "New Training"))
        self.actionSerial_Port.setText(_translate("MainWindow", "Serial Port"))
        self.actionAbout.setText(_translate("MainWindow", "About"))

from . import images_rc
