# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'newTraining.ui'
#
# Created by: PyQt5 UI code generator 5.4.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(750, 437)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(450, 380, 181, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setGeometry(QtCore.QRect(20, 70, 191, 301))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_7 = QtWidgets.QLabel(self.frame)
        self.label_7.setGeometry(QtCore.QRect(40, 20, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.stageComboBox = QtWidgets.QComboBox(self.frame)
        self.stageComboBox.setGeometry(QtCore.QRect(20, 60, 158, 27))
        self.stageComboBox.setObjectName("stageComboBox")
        self.stageComboBox.addItem("")
        self.stageComboBox.addItem("")
        self.stageComboBox.addItem("")
        self.stageComboBox.addItem("")
        self.stageComboBox.addItem("")
        self.stageComboBox.addItem("")
        self.frame_2 = QtWidgets.QFrame(Dialog)
        self.frame_2.setGeometry(QtCore.QRect(240, 70, 491, 301))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_8 = QtWidgets.QLabel(self.frame_2)
        self.label_8.setGeometry(QtCore.QRect(130, 20, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.frame_2)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(220, 60, 241, 181))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gridLayoutWidget_2.sizePolicy().hasHeightForWidth())
        self.gridLayoutWidget_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.gridLayoutWidget_2.setFont(font)
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.configuration = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.configuration.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.configuration.setContentsMargins(0, 0, 0, 0)
        self.configuration.setHorizontalSpacing(10)
        self.configuration.setVerticalSpacing(0)
        self.configuration.setObjectName("configuration")
        self.label = QtWidgets.QLabel(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.configuration.addWidget(self.label, 1, 0, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_14.sizePolicy().hasHeightForWidth())
        self.label_14.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.configuration.addWidget(self.label_14, 5, 3, 1, 1)
        self.gReward = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gReward.sizePolicy().hasHeightForWidth())
        self.gReward.setSizePolicy(sizePolicy)
        self.gReward.setMaximumSize(QtCore.QSize(50, 16777215))
        self.gReward.setObjectName("gReward")
        self.configuration.addWidget(self.gReward, 3, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.configuration.addWidget(self.label_6, 6, 3, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.configuration.addWidget(self.label_10, 5, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.configuration.addWidget(self.label_4, 3, 3, 1, 1)
        self.gStopPercent = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_2)
        self.gStopPercent.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gStopPercent.sizePolicy().hasHeightForWidth())
        self.gStopPercent.setSizePolicy(sizePolicy)
        self.gStopPercent.setDecimals(1)
        self.gStopPercent.setMaximum(1.0)
        self.gStopPercent.setSingleStep(0.1)
        self.gStopPercent.setProperty("value", 0.2)
        self.gStopPercent.setObjectName("gStopPercent")
        self.configuration.addWidget(self.gStopPercent, 7, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.configuration.addWidget(self.label_5, 6, 0, 1, 1)
        self.gLH = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gLH.sizePolicy().hasHeightForWidth())
        self.gLH.setSizePolicy(sizePolicy)
        self.gLH.setMaximumSize(QtCore.QSize(50, 16777215))
        self.gLH.setObjectName("gLH")
        self.configuration.addWidget(self.gLH, 1, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.configuration.addWidget(self.label_2, 3, 0, 1, 1)
        self.gPunishment = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gPunishment.sizePolicy().hasHeightForWidth())
        self.gPunishment.setSizePolicy(sizePolicy)
        self.gPunishment.setMaximumSize(QtCore.QSize(50, 16777215))
        self.gPunishment.setObjectName("gPunishment")
        self.configuration.addWidget(self.gPunishment, 6, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.configuration.addWidget(self.label_3, 1, 3, 1, 1)
        self.stopPercentLabel = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.stopPercentLabel.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stopPercentLabel.sizePolicy().hasHeightForWidth())
        self.stopPercentLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.stopPercentLabel.setFont(font)
        self.stopPercentLabel.setObjectName("stopPercentLabel")
        self.configuration.addWidget(self.stopPercentLabel, 7, 0, 1, 1)
        self.blinkerFreq = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.blinkerFreq.sizePolicy().hasHeightForWidth())
        self.blinkerFreq.setSizePolicy(sizePolicy)
        self.blinkerFreq.setMaximumSize(QtCore.QSize(50, 16777215))
        self.blinkerFreq.setObjectName("blinkerFreq")
        self.configuration.addWidget(self.blinkerFreq, 5, 2, 1, 1)
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.frame_2)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(30, 60, 171, 231))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.blockLengthLabel = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.blockLengthLabel.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.blockLengthLabel.sizePolicy().hasHeightForWidth())
        self.blockLengthLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.blockLengthLabel.setFont(font)
        self.blockLengthLabel.setObjectName("blockLengthLabel")
        self.gridLayout.addWidget(self.blockLengthLabel, 6, 0, 1, 1)
        self.gbaseline = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gbaseline.sizePolicy().hasHeightForWidth())
        self.gbaseline.setSizePolicy(sizePolicy)
        self.gbaseline.setMaximumSize(QtCore.QSize(50, 16777215))
        self.gbaseline.setInputMethodHints(QtCore.Qt.ImhNone)
        self.gbaseline.setObjectName("gbaseline")
        self.gridLayout.addWidget(self.gbaseline, 3, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 3, 0, 1, 1)
        self.direction_right = QtWidgets.QRadioButton(self.gridLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.direction_right.sizePolicy().hasHeightForWidth())
        self.direction_right.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.direction_right.setFont(font)
        self.direction_right.setObjectName("direction_right")
        self.gridLayout.addWidget(self.direction_right, 1, 1, 1, 1)
        self.gSessionLength = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gSessionLength.sizePolicy().hasHeightForWidth())
        self.gSessionLength.setSizePolicy(sizePolicy)
        self.gSessionLength.setMaximumSize(QtCore.QSize(50, 16777215))
        self.gSessionLength.setObjectName("gSessionLength")
        self.gridLayout.addWidget(self.gSessionLength, 5, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 0, 0, 2, 1)
        self.label_9 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 5, 0, 1, 1)
        self.blockLengthEdit = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.blockLengthEdit.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.blockLengthEdit.sizePolicy().hasHeightForWidth())
        self.blockLengthEdit.setSizePolicy(sizePolicy)
        self.blockLengthEdit.setMaximumSize(QtCore.QSize(50, 16777215))
        self.blockLengthEdit.setObjectName("blockLengthEdit")
        self.gridLayout.addWidget(self.blockLengthEdit, 6, 1, 1, 1)
        self.blockNumberEdit = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.blockNumberEdit.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.blockNumberEdit.sizePolicy().hasHeightForWidth())
        self.blockNumberEdit.setSizePolicy(sizePolicy)
        self.blockNumberEdit.setMaximumSize(QtCore.QSize(50, 16777215))
        self.blockNumberEdit.setObjectName("blockNumberEdit")
        self.gridLayout.addWidget(self.blockNumberEdit, 7, 1, 1, 1)
        self.blockNumberLabel = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.blockNumberLabel.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.blockNumberLabel.sizePolicy().hasHeightForWidth())
        self.blockNumberLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.blockNumberLabel.setFont(font)
        self.blockNumberLabel.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.blockNumberLabel.setObjectName("blockNumberLabel")
        self.gridLayout.addWidget(self.blockNumberLabel, 7, 0, 1, 1)
        self.direction_left = QtWidgets.QRadioButton(self.gridLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.direction_left.sizePolicy().hasHeightForWidth())
        self.direction_left.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.direction_left.setFont(font)
        self.direction_left.setChecked(True)
        self.direction_left.setObjectName("direction_left")
        self.gridLayout.addWidget(self.direction_left, 0, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(Dialog)
        self.label_13.setGeometry(QtCore.QRect(240, 30, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "New Training"))
        self.label_7.setText(_translate("Dialog", "Select Stage"))
        self.stageComboBox.setItemText(0, _translate("Dialog", "Stage 1"))
        self.stageComboBox.setItemText(1, _translate("Dialog", "Stage 2"))
        self.stageComboBox.setItemText(2, _translate("Dialog", "Stage 3"))
        self.stageComboBox.setItemText(3, _translate("Dialog", "Stage 4"))
        self.stageComboBox.setItemText(4, _translate("Dialog", "Test"))
        self.stageComboBox.setItemText(5, _translate("Dialog", "TestBox"))
        self.label_8.setText(_translate("Dialog", "Configurations"))
        self.label.setText(_translate("Dialog", "Limited \n"
"Hold:"))
        self.label_14.setText(_translate("Dialog", "<html><head/><body><p>s<span style=\" vertical-align:super;\">-1</span></p></body></html>"))
        self.gReward.setText(_translate("Dialog", "70"))
        self.label_6.setText(_translate("Dialog", "ms"))
        self.label_10.setText(_translate("Dialog", "BlinkerFreq:"))
        self.label_4.setText(_translate("Dialog", "ms"))
        self.label_5.setText(_translate("Dialog", "Punishment:"))
        self.gLH.setText(_translate("Dialog", "1500"))
        self.label_2.setText(_translate("Dialog", "Reward:"))
        self.gPunishment.setText(_translate("Dialog", "5000"))
        self.label_3.setText(_translate("Dialog", "ms"))
        self.stopPercentLabel.setText(_translate("Dialog", "Stop \n"
"Percent:"))
        self.blinkerFreq.setText(_translate("Dialog", "10"))
        self.blockLengthLabel.setText(_translate("Dialog", "Block\n"
"Length"))
        self.gbaseline.setText(_translate("Dialog", "20"))
        self.label_11.setText(_translate("Dialog", "Baseline \n"
"Length:"))
        self.direction_right.setText(_translate("Dialog", "L>R>M"))
        self.gSessionLength.setText(_translate("Dialog", "320"))
        self.label_12.setText(_translate("Dialog", "Direction:"))
        self.label_9.setText(_translate("Dialog", "Session \n"
"Length:"))
        self.blockLengthEdit.setText(_translate("Dialog", "100"))
        self.blockNumberEdit.setText(_translate("Dialog", "3"))
        self.blockNumberLabel.setText(_translate("Dialog", "Block\n"
"Number"))
        self.direction_left.setText(_translate("Dialog", "R>L>M"))
        self.label_13.setText(_translate("Dialog", "Training Settings"))

