# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../stopsignaltask_QtProject/newtraining.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(500, 400)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(150, 340, 181, 32))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.buttonBox.setFont(font)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(140, 10, 251, 51))
        font = QtGui.QFont()
        font.setFamily("Baskerville")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayoutWidget = QtWidgets.QWidget(Dialog)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(260, 80, 225, 221))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setObjectName("gridLayout")
        self.gLaserFreq = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.gLaserFreq.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.gLaserFreq.setFont(font)
        self.gLaserFreq.setMaximum(100)
        self.gLaserFreq.setObjectName("gLaserFreq")
        self.gridLayout.addWidget(self.gLaserFreq, 4, 1, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.gridLayout.addWidget(self.label_17, 3, 2, 1, 1)
        self.gPunishment = QtWidgets.QLineEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.gPunishment.setFont(font)
        self.gPunishment.setObjectName("gPunishment")
        self.gridLayout.addWidget(self.gPunishment, 3, 1, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.gridLayout.addWidget(self.label_18, 4, 2, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 1, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.gridLayout.addWidget(self.label_15, 2, 2, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 2, 0, 1, 1)
        self.gReward = QtWidgets.QLineEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.gReward.setFont(font)
        self.gReward.setObjectName("gReward")
        self.gridLayout.addWidget(self.gReward, 1, 1, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.gridLayout.addWidget(self.label_19, 6, 2, 1, 1)
        self.blinkerFreq = QtWidgets.QLineEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.blinkerFreq.setFont(font)
        self.blinkerFreq.setObjectName("blinkerFreq")
        self.gridLayout.addWidget(self.blinkerFreq, 2, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 6, 0, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.gridLayout.addWidget(self.label_16, 0, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 4, 0, 1, 1)
        self.gLaserDur = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.gLaserDur.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.gLaserDur.setFont(font)
        self.gLaserDur.setMinimum(100)
        self.gLaserDur.setMaximum(10000)
        self.gLaserDur.setObjectName("gLaserDur")
        self.gridLayout.addWidget(self.gLaserDur, 6, 1, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 1, 2, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 3, 0, 1, 1)
        self.gLH = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.gLH.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.gLH.setFont(font)
        self.gLH.setObjectName("gLH")
        self.gridLayout.addWidget(self.gLH, 0, 1, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.gridLayout.addWidget(self.label_21, 5, 0, 1, 1)
        self.gPulseDur = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.gPulseDur.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.gPulseDur.setFont(font)
        self.gPulseDur.setMaximum(100)
        self.gPulseDur.setObjectName("gPulseDur")
        self.gridLayout.addWidget(self.gPulseDur, 5, 1, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.gridLayout.addWidget(self.label_22, 5, 2, 1, 1)
        self.gridLayoutWidget_2 = QtWidgets.QWidget(Dialog)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(30, 80, 226, 221))
        font = QtGui.QFont()
        font.setFamily("Monaco")
        self.gridLayoutWidget_2.setFont(font)
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_7 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 4, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 2, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 5, 0, 1, 1)
        self.blockNumberEdit = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.blockNumberEdit.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.blockNumberEdit.setFont(font)
        self.blockNumberEdit.setObjectName("blockNumberEdit")
        self.gridLayout_2.addWidget(self.blockNumberEdit, 5, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 3, 0, 1, 1)
        self.stageComboBox = QtWidgets.QComboBox(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.stageComboBox.setFont(font)
        self.stageComboBox.setObjectName("stageComboBox")
        self.stageComboBox.addItem("")
        self.stageComboBox.addItem("")
        self.stageComboBox.addItem("")
        self.stageComboBox.addItem("")
        self.stageComboBox.addItem("")
        self.stageComboBox.addItem("")
        self.gridLayout_2.addWidget(self.stageComboBox, 0, 1, 1, 1)
        self.gbaseline = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.gbaseline.setFont(font)
        self.gbaseline.setObjectName("gbaseline")
        self.gridLayout_2.addWidget(self.gbaseline, 2, 1, 1, 1)
        self.directionComboBox = QtWidgets.QComboBox(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.directionComboBox.setFont(font)
        self.directionComboBox.setObjectName("directionComboBox")
        self.directionComboBox.addItem("")
        self.directionComboBox.addItem("")
        self.gridLayout_2.addWidget(self.directionComboBox, 1, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 1, 0, 1, 1)
        self.gSessionLength = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.gSessionLength.setFont(font)
        self.gSessionLength.setObjectName("gSessionLength")
        self.gridLayout_2.addWidget(self.gSessionLength, 3, 1, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.gridLayout_2.addWidget(self.label_20, 0, 0, 1, 1)
        self.blockLengthEdit = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.blockLengthEdit.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.blockLengthEdit.setFont(font)
        self.blockLengthEdit.setObjectName("blockLengthEdit")
        self.gridLayout_2.addWidget(self.blockLengthEdit, 4, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.gridLayout_2.addWidget(self.label_13, 6, 0, 1, 1)
        self.gStopPercent = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_2)
        self.gStopPercent.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.gStopPercent.setFont(font)
        self.gStopPercent.setDecimals(1)
        self.gStopPercent.setMaximum(1.0)
        self.gStopPercent.setSingleStep(0.1)
        self.gStopPercent.setProperty("value", 0.2)
        self.gStopPercent.setObjectName("gStopPercent")
        self.gridLayout_2.addWidget(self.gStopPercent, 6, 1, 1, 1)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:18pt; font-weight:600;\">Training Settings</span></p></body></html>"))
        self.label_17.setText(_translate("Dialog", "ms"))
        self.gPunishment.setText(_translate("Dialog", "5000"))
        self.label_18.setText(_translate("Dialog", "s-1"))
        self.label_10.setText(_translate("Dialog", "Reward:"))
        self.label_2.setText(_translate("Dialog", "LH:"))
        self.label_15.setText(_translate("Dialog", "s-1"))
        self.label_11.setText(_translate("Dialog", "BlinkerFreq:"))
        self.gReward.setText(_translate("Dialog", "70"))
        self.label_19.setText(_translate("Dialog", "ms"))
        self.blinkerFreq.setText(_translate("Dialog", "10"))
        self.label_9.setText(_translate("Dialog", "LaserDur:"))
        self.label_16.setText(_translate("Dialog", "ms"))
        self.label_3.setText(_translate("Dialog", "LaserFreq:"))
        self.label_14.setText(_translate("Dialog", "ms"))
        self.label_12.setText(_translate("Dialog", "Punishment:"))
        self.gLH.setText(_translate("Dialog", "1500"))
        self.label_21.setText(_translate("Dialog", "PluseDur:"))
        self.label_22.setText(_translate("Dialog", "ms"))
        self.label_7.setText(_translate("Dialog", "Block Length:"))
        self.label_5.setText(_translate("Dialog", "Baseline:"))
        self.label_8.setText(_translate("Dialog", "Block Number:"))
        self.blockNumberEdit.setText(_translate("Dialog", "3"))
        self.label_6.setText(_translate("Dialog", "Session length:"))
        self.stageComboBox.setItemText(0, _translate("Dialog", "Stage 1"))
        self.stageComboBox.setItemText(1, _translate("Dialog", "Stage 2"))
        self.stageComboBox.setItemText(2, _translate("Dialog", "Stage 3"))
        self.stageComboBox.setItemText(3, _translate("Dialog", "Stage 4"))
        self.stageComboBox.setItemText(4, _translate("Dialog", "Test"))
        self.stageComboBox.setItemText(5, _translate("Dialog", "TestBox"))
        self.gbaseline.setText(_translate("Dialog", "20"))
        self.directionComboBox.setItemText(0, _translate("Dialog", "R>L>M"))
        self.directionComboBox.setItemText(1, _translate("Dialog", "L>R>M"))
        self.label_4.setText(_translate("Dialog", "Direction:"))
        self.gSessionLength.setText(_translate("Dialog", "320"))
        self.label_20.setText(_translate("Dialog", "Stage:"))
        self.blockLengthEdit.setText(_translate("Dialog", "100"))
        self.label_13.setText(_translate("Dialog", "Stop Percent:"))

